In [1]:
import numpy as np

In [5]:
np_arr1 = np.array([1,2,3])

In [7]:
print(np_arr1) #넘파이와 Array의 구분

[1 2 3]


In [8]:
np_arr2 = np.array([1, 2.0, '3']) # 제일 메모리가 큰 String 타입으로 자동변환
print(np_arr2)

['1' '2.0' '3']


In [12]:
np_arr3 = np.array([1, 2.0, '3'], float) # float 타입으로 강제 지정
print(np_arr3)

[1. 2. 3.]


In [14]:
print(np_arr1.dtype)
print(np_arr2.dtype)
print(np_arr3.dtype)

int32
<U32
float64


In [16]:
print(np_arr1.shape) # 어떻게 생겼는지 표현
print(np_arr2.shape)
print(np_arr3.shape)

(3,)
(3,)
(3,)


In [18]:
np_arr1 = np.array([1,2,3])
print(np_arr1)

[1 2 3]


In [19]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [20]:
matrix.shape

(2, 3)

In [22]:
tensor = np.array([[[1, 2, 3], [4, 5, 6]], [[2, 3, 4], [5, 6, 7]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [ ]:
print(tensor)

: 

In [25]:
tensor.shape

(4, 2, 3)

# 배열
## 배열 생성 시 주의사항

In [27]:
np_arr4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) #shape이 같은경우
print(np_arr4)

[[1 2 3 4]
 [5 6 7 8]]


In [29]:
np_arr5 = np.array([[1, 2, 3], [5, 6, 7, 8]]) #shape이 다른 경우
print(np_arr5)

[list([1, 2, 3]) list([5, 6, 7, 8])]


C:\Users\chaos\AppData\Local\Temp\ipykernel_21320\3848360580.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np_arr5 = np.array([[1, 2, 3], [5, 6, 7, 8]]) #shape이 다른 경우


## 차원(rank) 확인
- ndim => dimension확인
- size => 전체 칸 갯수

In [31]:
print(np_arr1.ndim)
print(matrix.ndim)
print(tensor.ndim)

1
2
3


In [32]:
print(np_arr1.size)
print(matrix.size)
print(tensor.size)

3
6
24


## dtype : 자료형 지정 및 확인

In [44]:
np.array([[1, 2, 3], [4, 5, 6]], dtype = int).dtype

dtype('int32')

In [45]:
np.array([[1, 2, 3], [4, 5, 6]], dtype = np.int8).dtype

dtype('int8')

In [46]:
np.array([[1, 2, 3], [4, 5, 6]], dtype = np.float32).dtype

dtype('float32')

## nbytes : 자료형의 byte수 확인

In [47]:
np.array([[1, 2, 3], [4, 5, 6]], dtype = int).nbytes

24

In [48]:
np.array([[1, 2, 3], [4, 5, 6]], dtype = np.int8).nbytes

6

In [49]:
np.array([[1, 2, 3], [4, 5, 6]], dtype = np.float32).nbytes

24

In [50]:
tensor2 = np.array([[[10, 12, 33], [44, 15, 26]], [[24, 31, 43], [75, 86, 97]], [[10, 22, 13], [45, 125, 46]], [[1, 2, 3], [4, 5, 6]]])

In [51]:
print(tensor2)

[[[ 10  12  33]
  [ 44  15  26]]

 [[ 24  31  43]
  [ 75  86  97]]

 [[ 10  22  13]
  [ 45 125  46]]

 [[  1   2   3]
  [  4   5   6]]]


In [55]:
tensor2[0,1,2] # 26

26

In [58]:
tensor2[3, 0, 0] # 1

1

In [59]:
tensor2[2, 1, 1] # 125

125

## 배열 인덱싱 (fancy indexing)

In [64]:
# 기본 데이터
arr = np.array([1, 2, 3, 4, 5])
arr


array([1, 2, 3, 4, 5])

In [66]:
## Boolean 배열 방식
idx = [True, False, True, True, False]
arr[idx]

array([1, 3, 4])

In [67]:
# 정수배열 방식
idx = [0, 2, 3]
arr[idx]

array([1, 3, 4])

In [69]:
# 연산식 사용-1
arr % 2 == 0

array([False,  True, False,  True, False])

In [70]:
arr[arr % 2 ==0]

array([2, 4])

In [71]:
# 연산식 사용-2
(arr % 2 == 0) | (arr == 3)

array([False,  True,  True,  True, False])

In [73]:
arr[(arr % 2 == 0) | (arr == 3)] # | <=> or 연산자

array([2, 3, 4])

## 배열 슬라이싱

In [75]:
tensor2 = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[11, 12, 13], [14, 15, 16]],
    [[21, 22, 23], [24, 25, 26]],
    [[31, 32, 33], [34, 35, 36]]    
])
print(tensor2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]

 [[21 22 23]
  [24 25 26]]

 [[31 32 33]
  [34 35 36]]]


In [76]:
tensor2[:, 0, -1]

array([ 3, 13, 23, 33])

In [77]:
tensor2[1:, -1:, :-1]

array([[[14, 15]],

       [[24, 25]],

       [[34, 35]]])

In [78]:
matrix = np.array([
    [0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9],
    [10, 11, 12, 13, 14]
])


In [81]:
matrix[1, 1:3]

array([6, 7])

In [82]:
matrix[[1, 2], [2, 2]]

array([ 7, 12])

## 배열 생성 함수
- reshape : 재정의 # -1 => 행, 열 중 하나만 값을 넣어주면 나머지를 계산
- arange : range 함수와 비슷한 기능
- random.randn(n) : n 개의 랜덤값을 가지는 배열

In [86]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [88]:
np.arange(0, 2, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [89]:
np.arange(1, 26).reshape(5, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [91]:
tensor3 = np.arange(0, 30).reshape(3, 2, 5)

In [97]:
tensor3.sum()

435

In [98]:
tensor3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [93]:
tensor3.sum(axis = 0) # rank값끼리

array([[30, 33, 36, 39, 42],
       [45, 48, 51, 54, 57]])

In [94]:
tensor3.sum(axis = 1) # row값끼리

array([[ 5,  7,  9, 11, 13],
       [25, 27, 29, 31, 33],
       [45, 47, 49, 51, 53]])

In [96]:
tensor3.sum(axis = 2) # column값끼리

array([[ 10,  35],
       [ 60,  85],
       [110, 135]])